### ISSUE TITLE
Problem with rule included in world 648 (and any other X48)

### ISSUE THREAD

**Issue by brienc23** [504rules/504rules.github.io#102]
There was a section that read:

"There are no fights in cities, so any number of players may have their own trading houses there. The trading houses of free cities also count when calculating prices of player trading houses. If the player conquers a land tile, he also conquers an existing plant. If the land tile is neutralized, the plant remains abandoned for now."

But this was marked as 8.I in the book of worlds so it should not have shown up for this combination.  It did not make sense so was easily ignored, but wanted to report it so it doesn't trip up anyone else trying these combos.

Seems to happen in other X48 words as well.

**Comment by OsnaFonz** [comment]
It is now fixed.
