### ISSUE TITLE
The privilege I(2) should be used in X8X worlds

### ISSUE THREAD

**Issue by heron-da-cruz** [504rules/504rules.github.io#103]
var privilege_defs = { 
(...)
'2': {allow: ['2.I', '2.II', '4.II', '6.II', '7.II', '6.II', '9.I', '9.II'], disallow: [] }
(...)
}

should be

'2': {allow: ['2.I', '2.II', '4.II', '6.II', '7.II', '8.II', '9.I', '9.II'], disallow: [] }

**Comment by Arachnid** [comment]
Thanks for the bug report. Feel free to submit a PR!
