### ISSUE TITLE
12X or X21 worlds with residents shouldn't count residents settling for income

### ISSUE THREAD

**Issue by drbobjack1** [504rules/504rules.github.io#109]
As brought up here: https://boardgamegeek.com/article/22049752#22049752, the rulebook has an addendum for games played with the transport trolley. "In games with the module “Pick Up & Deliver“, the player **reaches a city only with his transport trolley**. In that case he places 1 resident from his storage on top of the matching city card. Of course, the player may move residents onto the city so they can settle there. This is simply not tracked on the city cards" (bolded for emphasis).

This seems like a special case rule overriding the general rule about residents settling to be placed on the city cards and produce income. Probably the normal bit about residents settling in phase 3D should no longer be included in this case (ex. 128).

Thanks so much for the great resource!

**Comment by someknave** [comment]
I believe the rules are now correct.
