### ISSUE TITLE
World 123 shows 48 goods instead of 40

### ISSUE THREAD

**Issue by SteveOliverC** [504rules/504rules.github.io#113]
In the 504 rules PDF, in the detailed explanation for World 123, it says to use 40 goods (8 each of all 5 types). But when I print out the page from the web site, it says 48 goods in the Special game parts section. (There are several other inconsistencies, too, such as the number of privilege cards.)

Later on the web site, under Game Preparation, says to use 4 goods on each city, which would be 40 goods.

I don't have my copy yet, so I don't know how this compares to what is in the Book of Worlds. 

Is the rules PDF wrong? or is the web site wrong?

**Comment by mcdemarco** [comment]
There's some discussion of this at BoardGameGeek: https://boardgamegeek.com/article/22894667#22894667

In short, the Book of Worlds shows 48 goods, because it's a more general explanation than the 123-specific one in the Book of Rules.  The website follows the Book of Worlds.
