### ISSUE TITLE
Word 8xx: Missing paragraph in Final Scoring

### ISSUE THREAD

**Issue by alexkazik** [504rules/504rules.github.io#117]
It is not mentioned in the Final Scoring paragraph that each Trading House scores 2 VP.
It is mentioned in the example above.

**Comment by mcdemarco** [comment]
I noticed you switched {{agent}} to player, but I think it should still be {{agent}}, e.g. for world #891.

**Comment by someknave** [comment]
the rules for end scoring  with module 9 are entirely separate so the agent tag isn't needed. look at the world 891 and see what the result is.
