### ISSUE TITLE
123 Possession at the start of the world

### ISSUE THREAD

**Issue by kerotm1024** [504rules/504rules.github.io#124]
Hello.
123 Because there are no residents in the world, the initial money at the start is not 60 dollars + 20 dollars, and in the case of 60 $, 70 $, 80 $, 90 $ (60 $, 80 $ if two players are in order) in order Is it not?

**Comment by refactoringdr** [comment]
No. The Starting Money is from Module I (Priority V) which gives each player $60 + Module III (Always) which adds $20. Plus, since 123 is the demo world and has explicit rules in the Rulebook, it is clear that the starting Money is $80.

**Comment by kerotm1024** [comment]
Thank you for your reply. I confirmed that the rules were different between the original and Japanese version. I apologize for the trouble.
