### ISSUE TITLE
Module 9 texts sometimes use "player" instead of "company"

### ISSUE THREAD

**Issue by JVor** [504rules/504rules.github.io#15]
I know this is a really tedious task to do, but there's still room for optimization regarding the combinations with module 9. An idea could be to try and replace "the player" with "the company" and "his" with "its" in the texts via JS if module 9 is in slot I or II. Might be better maintainable than tons of exceptions.

**Comment by Arachnid** [comment]
We're already maintaining separate text for this case due to limitations of the template engine, but I thought I'd caught all the instances of this when I went through it. Can you point out any specific cases that remain?

**Comment by JVor** [comment]
E.g. on http://504rules.github.io/#892:

Phase 3A: "At the start of his turn, the player …"
Phase 3D: "While moving, the residents are in a hurry. Thus, if the player …"
Mid-Term Scorings: "Award 5 VP from the stack set aside for this purpose to the first player …" (Also, this is incorrect; there's a special rule for 2.III in combination with 9.II where 1 VP is converted to 10 currency.)
Final Scoring: "The player takes the goods in front of him …"

This wording is taken from 8.I and 2.III respectively, so adjusting it to 9.II would mean more exceptions. I think something like this can be found for other X-9-Y combinations as well ...

**Comment by Arachnid** [comment]
Ah, you're right. The 'income' phase is correct because that's specific to this set of worlds, but the other ones that aren't directly affected by module 9 are as-is. Text replacement might work, but would likely miss some stuff. Another alternative would be to have a {{player}} token that gets replaced with "player" or "company" as appropriate. I'll leave this open for now as a feature request.

**Comment by someknave** [comment]
I have been working on creating a tags for agent (player/president), owner (player/company), and owners(his/their). my first few attempts have crashed my forked version of the repo. JS isn't my strong suit... well I should really say that programming isn't my strong suit.

**Comment by OsnaFonz** [comment]
the function is now included

**Comment by someknave** [comment]
Examples and sections for phase 3 E to phase 5 to go.

please let me know if there are issues with game prep and sections for phase 1 to 3 D

**Comment by someknave** [comment]
This has been largely completed. I'm not sure whether to call this closed at this point as the examples have yet to be done, and more work needs to be done to make this language compatible.
