### ISSUE TITLE
Mid-term Scorings for 5x2: 3 needed, not 1 (majority board must be used)

### ISSUE THREAD

**Issue by alextfish** [504rules/504rules.github.io#43]
Pages like http://504rules.github.io/#542 imply (in the "Mid-Term Scoring" section at the end) that the first player to explore a desert gets 5VP, as does the first player to explore a plains, etc.

However, discussions like https://boardgamegeek.com/thread/1470682/5x2-and-952-set-and-mid-game-scoring-especially-ca make it clear that this mid-term VP should go to the player who first explores _three_ deserts, and to the player who first explores _three_ plains, etc. The majority board should be used to track players' progress towards these goals.

The 504rules web page doesn't mention doing anything with the majority board at all except getting it out, which is clearly wrong.

**Comment by someknave** [comment]
This has been fixed
