### ISSUE TITLE
Feature request: Make 9.2 fill in income rules automatically

### ISSUE THREAD

**Issue by drbobjack1** [504rules/504rules.github.io#5]
It would be very useful if we could see the income rules from the page for a given x9x world, instead of having to continue turning back and forth.

Thanks!

**Comment by Arachnid** [comment]
Can you give an example of what's not shown? I'm not sure I follow.

**Comment by JVor** [comment]
E.g. if you select 89X, Phase 3H: Income just says "Follow the rules regarding the income of module on TOP 1. Place the income of the stock company separate from the company assets to the side for now."

It would be great to see the rules from the module on TOP 1 there.

**Comment by Arachnid** [comment]
Ah, right, good catch. That's a bit awkward because it will require duplicating the entire 'income' section for that special case, which is awkward, but you're right that some sort of solution needs to be found.

**Comment by JVor** [comment]
Now I get

Uncaught Error: Unclosed section "6.I" at 75551

**Comment by Arachnid** [comment]
Oops. Fixed now.

Sections still refer to 'player' instead of 'company', so I'm leaving this open for now.

**Comment by drbobjack1** [comment]
Cool, thanks!
