### ISSUE TITLE
Latest version will not load on iPad

### ISSUE THREAD

**Issue by refactoringdr** [504rules/504rules.github.io#55]
It actually causes Safari to crash.

**Comment by refactoringdr** [comment]
It seems intermittent. It might be a size issue. I'll let you know if I can pin it down.

**Comment by refactoringdr** [comment]
In its current incarnation, the page crashes mobile safari more often than not. I'm not enough of a web wizard to isolate the cause, but it seems JavaScript-related. I've tried debugging it using the developer tools on Desktop Safari, but it doesn't crash there.

**Comment by someknave** [comment]
it might be the cache.

**Comment by refactoringdr** [comment]
It was crashing before appcache. I still haven’t figured out why, but it beats the heck out of mobile safari..

don

**Comment by OsnaFonz** [comment]
i think it is fixed for now :-)

**Comment by refactoringdr** [comment]
Awesome! Thanks.
