### ISSUE TITLE
Colour code rules?

### ISSUE THREAD

**Issue by someknave** [504rules/504rules.github.io#76]
Is it worth having some kind of token/tag that puts some colour at the start of a line based on the module that affected that rule? I'm not sure how this would look graphically but I think it would be neat if there was some visual clue as to where the rule came from.

This could just be used to change the colour of the section headings that relate to specific modules.
Or there could be a small square coloured block at the beginning of each small paragraph.

This would definitely be an enhancement and is by no means necessary. It's just that now that we have the colours in the randomiser it makes some sense to integrate them into the rules somehow.

**Comment by OsnaFonz** [comment]
Funny, I have thought about the exact same thing when I created the color list.  I will make some tests in my rep, how to include this color coding.

**Comment by someknave** [comment]
The more I think about it the more I like the idea of the sidebar for the different phases being coloured by the module that they are mostly from  (some sections are not from any particular module and some can be from multiple).
So income would be from pos II
game end and final scoring would be from pos I
phase 3e trolley movement would be module 1 coloured
phase 3g fights would be module 4 coloured.
etc.

**Comment by Arachnid** [comment]
It think it could look good, or like a rainbow in a traffic accident. I'd be interested to see which it turns out like!

**Comment by OsnaFonz** [comment]
you can take a look at the implementation at http://osnafonz.github.io/504rules.github.io/

**Comment by Arachnid** [comment]
That URL is 404; did you take your repo down?

**Comment by OsnaFonz** [comment]
I have just updated it. it should work now.

**Comment by Arachnid** [comment]
It looks good to me. Maybe a number in a circle for those of us who are color-blind, too?

**Comment by OsnaFonz** [comment]
mmh, how important do you think is the color information. i think it is more a gimmick, than a useful information.

**Comment by Arachnid** [comment]
Yes, you're probably right.

**Comment by someknave** [comment]
That turned out really well. It does convey that basic level of information. Nice work.

**Comment by OsnaFonz** [comment]
It's now included in the repo.
