### ISSUE TITLE
Include exact privilege list in game preperation

### ISSUE THREAD

**Issue by someknave** [504rules/504rules.github.io#81]
It doesn't seem like it would be too hard to create a privilege list, (like the game parts list) and each module section would include the privileges that it adds to the game. the only slightly more tricky ones are the vp privileges that aren't included with module 9.I (and 3.III for the 5 point), also there are some that are only included when playing with residents.

**Comment by someknave** [comment]
Thanks Fonz, I am having issues with running another function based on the priv object that you created.I have been trying to express the privileges as a text string:
 https://github.com/someknave/504rules.github.io/blob/master/index.html

When I console printed the output of catchPrivileges it appeared as an array rather than an object, is that the source of my issue? or am I missing something else?

**Comment by OsnaFonz** [comment]
i reorganized the cards_def a little bit. because in world 523 for example there are no step III cards. so the headline is unnecessary. i added a flag if there are cards for each step. and i included your card list.

**Comment by OsnaFonz** [comment]
btw. there are some problems in your function, but my bad english knowledge prevented that i can easily explain it to you. sorry for that

**Comment by someknave** [comment]
No worries. I am an absolute novice here. I have a little background in programming in general. And have enough html knowledge that using mustache is fairly intuitive but anything that requires me to actually have a working knowledge of JavaScript is beyond me.

**Comment by OsnaFonz** [comment]
what do you guys think about the idea to put the card list with rules to the bottom of the printview as an extra sheet on one single page?

**Comment by someknave** [comment]
I think that's best.

**Comment by someknave** [comment]
this has been resolved
