### ISSUE TITLE
Phase 3C

### ISSUE THREAD

**Issue by hajott59** [504rules/504rules.github.io#9]
In all worlds with residents, you play with Phase 3C = Purchase residents for 10$ each.
Maybe its a good idea to add this note in the sequence of play.

Additional, a note in the headline whether you play the world with or without residents may be helpful.

**Comment by mratin** [comment]
+1
Even though this information isn't available in the BoW either, I agree that it would be very convenient to include it here.

**Comment by Arachnid** [comment]
Both good points, thanks.

**Comment by Arachnid** [comment]
Looking at this closer, I'm no longer sure it's a good idea. What's special about Phase 3 C? If I include that, I should probably include all the other rules (other than setup, perhaps), and it'll definitely no longer be possible to fit everything on two sides.

I think this would be better left for an 'extended' option that inlines the entire ruleset rather than the current quick-reference format.

**Comment by hajott59** [comment]
Hello Nick,

Its nothing special about Phase 3C, but for the complete sequence in all games with residents, when this phase occur,
in my opinion, one line as a reminder is a clarity of the course of the game.

Have a nice sunday

Hans-Joerg
  ----- Original Message -----

**Comment by Arachnid** [comment]
The rest of phase 3c also takes place, though - movement, exhausting, etc. Why include the buy instruction but not the rest?

**Comment by hajott59** [comment]
Hello Nick,

there is no rest of phase 3C. Movement, Exhausting, Actions etc. is Phase 3D.
And Phase 3D has several specials, that changes and/or adds something to the basic
rules, as described in the Book of Worlds.

Phase 3C - in alle games with residents - is a one liner:
PURCHASE RESIDANTS FOR 10$ EACH AND PLACE IT ON THE BOARD.
It is always the same, there is no change of the basic rules.
But I find it important at least as a reminder for a completely summery of the game-sequence.
Without this, you have always to notice: You play with residents, ah, look out, there is a
phase 3C .... this phase is always absent in the course of the game presentation, but it happens.

Its not a great thing, but as a rule pedant, I find it better with the display of Phase 3C :-)

Have a nice day

Hans-Joerg
  ----- Original Message -----

**Comment by someknave** [comment]
Buy instruction has been included but there are no details about how placement works.
